In [1]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import rand, seed

In [2]:
# EXAMPLE OF A STATIONARY k-BANDIT PROBLEM
# Parameters
NK = 2
seed(1234)

# Initialize actual distribution of each bandit
NMEANS = np.random.normal(loc=0.0, scale=1.0, size=NK)

print(NMEANS)

[ 0.47143516 -1.19097569]


In [3]:
seed(1234)
def optimal_action(qvalue, eps):
    """
    Determines what is the action to take given a measure of past
    expected rewards across actions. With probability eps the action
    is not the greedy one
    """
    nactions = qvalue.shape[0]
    action_hat = np.where(qvalue == np.max(qvalue))

    if rand() <= eps:
        randnum = rand()
        for aa in range(nactions):
            if randnum < (aa + 1) / nactions:
                break
    elif action_hat[0].shape[0] > 1:
        # Randomize action when ties
        randnum = rand()
        for aa in range(action_hat[0].shape[0]):
            if randnum < (aa + 1) / action_hat[0].shape[0]:
                break
        aa = action_hat[0][aa]
    else:
        aa = np.argmax(qvalue)

    return aa

In [13]:
seed(1234)
def reward_update(action, reward, qvalue_old, alpha):
    qvalue_new = qvalue_old.copy()

    qvalue_new[action] = qvalue_old[action] + alpha * (reward - qvalue_old[action])

    return qvalue_new

In [5]:
qvalue = np.zeros((NK))
nchoices = np.zeros((NK))
epsilon = 0.1

In [6]:
seed(1234)
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])

In [7]:
seed(1234)
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])

In [8]:
seed(1234)
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])

In [9]:
qvalue

array([-0.56219613, -0.99143786])

In [10]:
nchoices

array([1., 2.])

In [11]:
seed(1234)
qvalue = np.zeros((NK))
nchoices = np.zeros((NK))
EPSILON = 0
ALPHA = 0.25

In [12]:
aa_opt = optimal_action(qvalue, EPSILON)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1 
qvalue = reward_update(aa_opt, reward, qvalue, ALPHA)

In [7]:
seed(1234)
def optimal_action(qvalue, eps):
    """
    Determines what is the action to take given a measure of past
    expected rewards across actions. With probability eps the action
    is not the greedy one
    """
    nactions = qvalue.shape[0]
    action_hat = np.where(qvalue == np.max(qvalue))

    if rand() <= eps:
        randnum = rand()
        for aa in range(nactions):
            if randnum < (aa + 1) / nactions:
                break
    elif action_hat[0].shape[0] > 1:
        # Randomize action when ties
        randnum = rand()
        for aa in range(action_hat[0].shape[0]):
            if randnum < (aa + 1) / action_hat[0].shape[0]:
                break
        aa = action_hat[0][aa]
    else:
        aa = np.argmax(qvalue)

    return aa

def reward_update(action, reward, qvalue_old, alpha):
    qvalue_new = qvalue_old.copy()

    qvalue_new[action] = qvalue_old[action] + alpha * (reward - qvalue_old[action])

    return qvalue_new

NK = 2

# Initialize actual distribution of each bandit
NMEANS = np.random.normal(loc=0.0, scale=1.0, size=NK)

qvalue = np.zeros((NK))
nchoices = np.zeros((NK))
epsilon = 0.75
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])
#2
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])
#3
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])

In [8]:
qvalue

array([ 0.14082834, -1.10768859])

In [24]:
seed(1234)
def optimal_action(qvalue, eps):
    """
    Determines what is the action to take given a measure of past
    expected rewards across actions. With probability eps the action
    is not the greedy one
    """
    nactions = qvalue.shape[0]
    action_hat = np.where(qvalue == np.max(qvalue))

    if rand() <= eps:
        randnum = rand()
        for aa in range(nactions):
            if randnum < (aa + 1) / nactions:
                break
    elif action_hat[0].shape[0] > 1:
        # Randomize action when ties
        randnum = rand()
        for aa in range(action_hat[0].shape[0]):
            if randnum < (aa + 1) / action_hat[0].shape[0]:
                break
        aa = action_hat[0][aa]
    else:
        aa = np.argmax(qvalue)

    return aa

def reward_update(action, reward, qvalue_old, alpha):
    qvalue_new = qvalue_old.copy()

    qvalue_new[action] = qvalue_old[action] + alpha * (reward - qvalue_old[action])

    return qvalue_new

NK = 2

# Initialize actual distribution of each bandit
NMEANS = np.random.normal(loc=0.0, scale=1.0, size=NK)

qvalue = np.zeros((NK))
nchoices = np.zeros((NK))
EPSILON = 0.25
ALPHA = 0.25
#1
aa_opt = optimal_action(qvalue, EPSILON)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1 
qvalue = reward_update(aa_opt, reward, qvalue, ALPHA)
#2
aa_opt = optimal_action(qvalue, EPSILON)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1 
qvalue = reward_update(aa_opt, reward, qvalue, ALPHA)
#3
aa_opt = optimal_action(qvalue, EPSILON)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=1.0)
nchoices[aa_opt] += 1 
qvalue = reward_update(aa_opt, reward, qvalue, ALPHA)

In [25]:
qvalue

array([ 0.37652003, -0.47789111])

In [22]:
seed(1234)
def optimal_action(qvalue, eps):
    """
    Determines what is the action to take given a measure of past
    expected rewards across actions. With probability eps the action
    is not the greedy one
    """
    nactions = qvalue.shape[0]
    action_hat = np.where(qvalue == np.max(qvalue))

    if rand() <= eps:
        randnum = rand()
        for aa in range(nactions):
            if randnum < (aa + 1) / nactions:
                break
    elif action_hat[0].shape[0] > 1:
        # Randomize action when ties
        randnum = rand()
        for aa in range(action_hat[0].shape[0]):
            if randnum < (aa + 1) / action_hat[0].shape[0]:
                break
        aa = action_hat[0][aa]
    else:
        aa = np.argmax(qvalue)

    return aa

def reward_update(action, reward, qvalue_old, alpha):
    qvalue_new = qvalue_old.copy()

    qvalue_new[action] = qvalue_old[action] + alpha * (reward - qvalue_old[action])

    return qvalue_new

NK = 2

# Initialize actual distribution of each bandit
NMEANS = np.random.normal(loc=0.0, scale=0.5, size=NK)

qvalue = np.zeros((NK))
nchoices = np.zeros((NK))
epsilon = 0.0
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=0.5)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])
#2
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=0.5)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])
#3
aa_opt = optimal_action(qvalue, epsilon)
reward = np.random.normal(loc=NMEANS[aa_opt], scale=0.5)
nchoices[aa_opt] += 1  # update with avg. number of times aa_opt was chosen
qvalue = reward_update(aa_opt, reward, qvalue, 1 / nchoices[aa_opt])

In [23]:
qvalue

array([ 0.46143241, -0.95578221])

In [17]:
aa_opt

1